### PR TITLE
Indexing settings and logging improve

### PR DESCRIPTION
**Pull request by AlexandrSher**

### CODE REVIEW

**Review by yuhongsun96 — APPROVED** [review]
Great stuff, thanks for the contribution!
One tiny thing, I had to remove the logic to add the incrementing _1 to the name, it's suppose to be unique as a way to verify that the caller isn't doing something wrong.

**Comment by AlexandrSher** [comment]
> Great stuff, thanks for the contribution! One tiny thing, I had to remove the logic to add the incrementing _1 to the name, it's suppose to be unique as a way to verify that the caller isn't doing something wrong.

yes but we have some scope in jira and wiki with the same name (it's not unique case). So we have to add _1 to start index at all :(
May be you can do something better then add _1 to resolve this one?

**Comment by yuhongsun96** [comment]
Got it, let me think about this one

**Comment by yuhongsun96** [comment]
Ok I removed the unique constraint, you should be able to create a Jira and Confluence connector that resolve to the same name. v0.3.7 has it and it's in main as well now

**Comment by AlexandrSher** [comment]
> Ok I removed the unique constraint, you should be able to create a Jira and Confluence connector that resolve to the same name. v0.3.7 has it and it's in main as well now

Thank you a lot!

**Comment by yuhongsun96** [comment]
Hi @AlexandrSher, Happy New Year!

We're trying to reach out and talk to our users to understand what use cases people/teams have been finding the most success with Danswer. We'd love to hear from you and get your feedback!

Would you be open to to joining our [Slack](url) or pick a quick time to chat with us on my [Cal](https://app.cal.com/yuhongsun/15min)?

**Pull request merged**
