### PR TITLE
Replace format characters from string when indexing

### PR DESCRIPTION
**Pull request by pitzcarraldo**
Hi Danswer team.

I tried to setup Danswer for my google drive documents, but had some issues with my documents that included Korean characters with some format characters. (Such as \x08, \x00)

My google drive connector failed to index with the below error.

`400 Client Error: Bad Request for url: http://index:8081/document/v1/default/danswer_chunk/docid/a8a8ce74-a450-567d-b4d0-ebf2d6576d1a`

And this is the reason of the 400 error.
`The string field value contains illegal code point 0x8: The string field value contains illegal code point 0x8`.

When google connector scrapes string it encodes format characters for some reason and it makes to fail to index.
So I added a function to replace them with whitespaces and I succeeded in indexing my google drive documents.

And there was another issue to export files from google drive with 403 error. When the connector gets 403, the whole indexing is failed.

So I made a change to ignore and continue indexing when get 403 response.

Now my whole indexing is working fine.
Here are my changes to make my system work.
Hope this could be helpful to someone.

### CODE REVIEW

**Comment by fan-wen** [comment]
Having the same issue here:(


Client error '400 Bad Request' for url 'http://index:8081/document/v1/default/danswer_chunk/docid/54918ff1-6d6f-579b-8644-c674a71c954d' For more information check: https://httpstatuses.com/400

**Comment by Weves** [comment]
Hey @pitzcarraldo, thanks a bunch for the PR. 

We have a function which is pretty similar to your `_replace_format_chars` function (https://github.com/danswer-ai/danswer/blob/main/backend/danswer/document_index/vespa/utils.py#L9), and I believe functionally they should be pretty much the same thing. We recently added the `title` Vespa field and did not apply it there, which is probably what's causing this issue to pop up again. This should be fixed in https://github.com/danswer-ai/danswer/pull/895, but do let me know if you're still running into any issue here. 

@fan-wen if you get a chance to pull this in, let me know if it solves your issue as well. If not happy to look into it more / see if there are any differences between the approach taken in this PR and the one that is live now.


For the `403` errors, do you know what type of error you were getting? I think your approach is reasonable, but before skipping these errors by default I'd like to get a little bit better understanding of what's going on. As an FYI, we also have a `CONTINUE_ON_CONNECTOR_FAILURE` env variable which works for Google Drive / Confluence and should make the indexing continue on these types of errors

**Comment by pitzcarraldo** [comment]
Hi @Weves, thanks for reply.
I don't mind if my changes aren't reflected as long as you already fixed the problem and you may close this PR. It is difficult to check which file in Google Drive caused the 403 error because logs have already been expired. I made this change to make my environment work. If the problems mentioned in this PR are resolved in the main branch, I would try to rebuild and configure my environment in the main branch and let you know if the problem reproduces.

Thanks :)

**Comment by Weves** [comment]
fyi @fan-wen @pitzcarraldo, put in another fix for this https://github.com/danswer-ai/danswer/pull/896. We did apply it to all the content-type fields (https://github.com/danswer-ai/danswer/blob/64d2cea39608fb1ed40a78359402ccca8ac75305/backend/danswer/document_index/vespa/index.py#L301), but this was never being hit since the exception type changed from `HTTPError` to `HTTPStatusError` with the switch from `requests` -> `httpx`. This should now be fixed in full 🙏

**Comment by pitzcarraldo** [comment]
Hi @Weves. Thanks for updates. Will let you know after testing main branch version on my env.

**Comment by yuhongsun96** [comment]
Closing as it's been addressed in another PR. Thanks for noticing it and bringing it to our attention! If you still encounter issues after upgrading, feel free to reopen.

**Comment by pitzcarraldo** [comment]
Hi folks, I updated danswer to the latest version, it seem the issue has been fixed.
Thanks :)

**Pull request closed without merging**
