### PR TITLE
Helm Chart Support

### PR DESCRIPTION
**Pull request by JayGhiya**
Have added helm charts and externalised all possible values in values.yaml.

Currently the pr is not ready to be merged facing weird issue with web server.

### CODE REVIEW

**Comment by JayGhiya** [comment]
current issue is : nginx not forwarding request to webserver for helm charts. post this chart would be in usable state. Debugging!

**Comment by JayGhiya** [comment]
ok issue is resolved. indentation issues haha in reading env! Now doing final testing.

**Comment by JayGhiya** [comment]
Charts have resource requirements added in except web server. The charts are ready for usage @yuhongsun96 :)

**Comment by JayGhiya** [comment]
@yuhongsun96 the pr from #1186 looks more feature complete when it comes to helm standards. thanks Arnaud :) . @arnaud-ritti. i will combine missing piece such as OpenEbs storage for readwritemany so that it becomes deployable locally or any self hosted cloud which does not provide nfs out of box. Also as arnaud's pr is more feature complete when it comes to helm standards lets discard this one once we take useful. things from this pr and merge from #1186 .

**Comment by JayGhiya** [comment]
so we both had a call me and @arnaud-ritti . we will be closing this pr as we will be working primarily from #1186 .

**Comment by JayGhiya** [comment]
Current tasks:

- [x] Create Hosted Vespa charts For Upstream so that could be used directly. 
- [ ] Add Vespa Hosted Charts as Dependency and override values as per danswer requirements in parent values.yaml
- [x] Add Nginx as Dependency and override values as per danswer requirements in parent values.yaml
- [ ] Add OpenEbs as Depenency and override values as per danswer requirements in parent values.yaml
- [ ] Add Resource Requirments as per Danswer resource recommendations.
- [x] Add Github CI/Cd for packaging and hosting danswer helm chart.
- [ ] Add Documentation for the same.

**Comment by JayGhiya** [comment]
also cc: @yuhongsun96 this pr already contains helm charts without subchart mechanism allowing people to try through helm. once subchart mechanism is complete we will remove the non-standard helm charts

**Comment by yuhongsun96** [comment]
Hey folks, in the latest version, we've removed the shared volume between the api server container and background container. It's all been moved to Postgres. Hopefully this simplifies things for the Helm deployment as well!

Is https://github.com/danswer-ai/danswer/pull/1186 the more recent one you guys are working on? I can review/test that one if it's ready

**Comment by JayGhiya** [comment]
1177 is where we are working right now. Yes so this is good. It should simplify the helm deployment. There is a checklist that has been created just above this comment so that is what we are following. Openebs/nfs is not required right now. Hopefully today or tomr aft completing checklist we could start testing

**Comment by yuhongsun96** [comment]
Oh, I thought the other PR was the more recent one, apologies for the confusion! May need to rebase 😅 
A couple questions/comments:

- I saw in https://github.com/danswer-ai/danswer/pull/1186, nginx was gone and replaced by some ingress options. We use nginx to rewrite some of the paths so if not then this API_PREFIX env variable has to be set. I prefer not removing nginx though as it's best to keep the deployments the same across different options like docker compose, k8s yamls, helm.

- In this one, I see there some some significant amount of duplicate code and 2 sets of charts, I prefer the layout of https://github.com/danswer-ai/danswer/pull/1186, it looked very reasonable.

- We want to get it to a point where running helm install just works with no modifications so people can easily test it out on minikube or docker desktop. Having a working base state makes customizing much easier.

- The shared volumes are not necessary anymore. The only two required persistent storage is for Postgres and Vespa now. Additionally an optional one to have would be the model cache https://github.com/danswer-ai/danswer/blob/main/deployment/docker_compose/docker-compose.dev.yml#L77 but this does not need to be shared between the services

I'll be available now to work closely with you guys to get this finalized. I'm not familiar with Helm but I'm happy to share knowledge on how the rest of the stuff works and interacts

**Comment by JayGhiya** [comment]
amazing right @yuhongsun96 . so we are going to keep nginx. and yes the layout is going to be based out of 1186. And yes we want to make sure that it runs easily on minikube or docker desktop.

**Comment by JayGhiya** [comment]
@yuhongsun96 the charts now are in good shape. model serving and resource spec is pending. once done we could start testing tomr. also get on a quick call tomr whenever convenient for you so we could release. also you could start reviewing and provide feedback.

**Comment by JayGhiya** [comment]
@yuhongsun96 finishing up inference related things and can we sync up real fast tomr for the same?

**Comment by yuhongsun96** [comment]
Ya sure thing! How about Thursday? Do you want to pick a time to sync on my Cal? https://cal.com/yuhongsun

**Comment by JayGhiya** [comment]
Sure leme do that thanks @yuhongsun96 😇

**Comment by JayGhiya** [comment]
Overall skeleton is ready with everything. Now will be doing minor brushing up on resources to align with helm standards how much ever  we could do now then lets start testing. cc: @yuhongsun96

**Comment by after-ephemera** [comment]
Hey folks @JayGhiya @yuhongsun96 , I'm interested in self-hosting a prototype of Danswer for my org and I'd love to be an early tester of the Helm chart. Will you let me know if now is a good time or if I should wait for 
> minor brushing up on resources to align with helm standards
? Thanks for the big lift!

**Comment by JayGhiya** [comment]
@after-ephemera yea so just finalising/testing resources/config. will ping here in a day or two when the charts would be ready for testing. Thankyou for volunteering.

**Comment by JayGhiya** [comment]
@yuhongsun96  as discussed adding the file to check config. Goal is to check resources and all possible config for all infrastructure and danswer stack components
[unoplat-template.yaml.zip](https://github.com/danswer-ai/danswer/files/14958113/unoplat-template.yaml.zip)

**Comment by JayGhiya** [comment]
@after-ephemera please start testing from tomorrow. and give feedbacks here. i will be monitoring this . thankyou again for volunteering. cc: @yuhongsun96

**Comment by JayGhiya** [comment]
@yuhongsun96 i will start testing this tomr and keep posting updates here

**Comment by slovx2** [comment]
Hey, @JayGhiya . Thank you very much for providing helm support. I am preparing to test these helm charts on my cluster and optimize them at the same time. I have a few questions I'd like to understand first:

- Can we provide an option to share the indexing_model_server and inference_model_server? My cluster resources are limited and I'd like to save some memory used for model loading.

- I noticed that the storage volumes are using predefined PVCs; is there a special reason for this? Can we use storage classes instead? This question arises because the implementation of PVCs varies across different IPSs, and often requires manual creation and modification.

**Comment by JayGhiya** [comment]
@slovx2 sure the first one needs more information. when you say share? do you want them to run from same pod with different ports? if that is the case @yuhongsun96 is the best person to answer. 
Regarding second query. In Kubernetes, the Persistent Volume Claim (PVC) is what triggers the creation of a Persistent Volume (PV), but it is the Storage Class that defines how the PV is provisioned and managed. So what is missing right now is externalised storage class. That definitely should be done so yea. I hope this answers your concern. if not leme know

**Comment by JayGhiya** [comment]
@yuhongsun96 initial testing done fixed couple of bugs. need one more round to get all stuff up and running. right now there is a issue where the sub charts are being pulled from 
"https://unoplat.github.io/vespa-helm-charts ".
Individually the charts work well. - https://github.com/unoplat/vespa-helm-charts . so trying to figure out why the subcharts for vespa fail. the subcharts for nginx and postgres work well from bitnami so we should be able to fix :)

**Comment by yuhongsun96** [comment]
Thanks for all your amazing work! Let me know when I should give it a test! If it can work out of the box with minikube, we can put it in :D

**Comment by acquia-ankith** [comment]
@JayGhiya, I have checked out your changes, was able to resolve all the issues and tested it locally with successful results. Could you or someone else please advise on the next steps for this pull request? Thank you!

**Comment by JayGhiya** [comment]
> @JayGhiya, I have checked out your changes, was able to resolve all the issues and tested it locally with successful results. Could you or someone else please advise on the next steps for this pull request? Thank you!

Thankyou for solving pending issues. I will add you as a collaborator then you could collab with me on same issue.

**Comment by JayGhiya** [comment]
> > @JayGhiya, I have checked out your changes, was able to resolve all the issues and tested it locally with successful results. Could you or someone else please advise on the next steps for this pull request? Thank you!
> 
> Thankyou for solving pending issues. I will add you as a collaborator then you could collab with me on same issue. 

Have added you as collaborator. You could push to the same pr.Also if you have less of time and want to get this done asap we can get on a call tomr if that works for you.

**Comment by acquia-ankith** [comment]
@JayGhiya  I have pushed my changes to same PR. Checkout my changes and test locally. We can have a call if required, I'm free tomorrow.

**Comment by JayGhiya** [comment]
> @JayGhiya I have pushed my changes to same PR. Checkout my changes and test locally. We can have a call if required, I'm free tomorrow.

thankyou @acquia-ankith will test this tomr and then we could get @yuhongsun96 for final tests and then release :)

**Comment by JayGhiya** [comment]
@acquia-ankith i have commented for one change and fixed one image issue. thats all post that i can check.

**Comment by acquia-ankith** [comment]
@JayGhiya  It looks good. But regarding the secrets for postgres_username and postgres_password, the existing secrets route didn't work for me locally, it was throwing authentication failed error in API Server. So I used the auth.username and auth.password to set those and used the same to set env variables in api-deployment.yaml and background-deployment.yaml files.

**Comment by JayGhiya** [comment]
> @JayGhiya  It looks good. But regarding the secrets for postgres_username and postgres_password, the existing secrets route didn't work for me locally, it was throwing authentication failed error in API Server. So I used the auth.username and auth.password to set those and used the same to set env variables in api-deployment.yaml and background-deployment.yaml files. 

Sure yea that shud be fixed. I am working towards finding why authentication issue occurs.

**Comment by JayGhiya** [comment]
@acquia-ankith @yuhongsun96 charts are in good shape. please start testing then could work with @yuhongsun96 on github actions for packaging/signing charts with automatic release changelog

**Comment by JayGhiya** [comment]
@acquia-ankith brother if you could start testing basic features of danswer and also optimise on resources(it takes time right now) according to danswer documentation it would of huge help.

**Comment by JayGhiya** [comment]
Most of resources are fixed. tested github connector :
image

cc: @yuhongsun96  @acquia-ankith thankyou guys

**Comment by JayGhiya** [comment]
@yuhongsun96 we could release charts now and then work towards improvements :) . Guys have been waiting for eternity and i feel guilty lets release

**Comment by JayGhiya** [comment]
Shoutout to @arnaud-ritti too for base helm charts . Will request you to test and provide feedback we could take all the feedback onto different issues post this release  @arnaud-ritti

**Comment by yuhongsun96** [comment]
Thank you all so much for the amazing work! I will test it in the morning!

**Comment by yuhongsun96** [comment]
Looks good, somehow nginx isn't working for me out of the box but I can iterate on top of this.

Great work!

**Review by yuhongsun96 — APPROVED** [review]

**Comment by JayGhiya** [comment]
Okay i checked lkcalhost:3000 while testing it worked. But it takes a while to come up. @acquia-ankith did you get a chance to try

**Comment by acquia-ankith** [comment]
@JayGhiya I tried to install helm charts using main branch after merge. I am getting following error in web server pod.

`2024-05-09 11:22:43 Error fetching user: TypeError: fetch failed
2024-05-09 11:22:43 Some fetch failed for the main search page - TypeError: fetch failed
2024-05-09 11:22:43 TypeError: fetch failed
2024-05-09 11:22:43     at node:internal/deps/undici/undici:12618:11
2024-05-09 11:22:43     at async globalThis.fetch (/app/.next/server/chunks/1638.js:1:36428)
2024-05-09 11:22:43     at async Promise.all (index 0)
2024-05-09 11:22:43     at async l (/app/.next/server/chunks/5566.js:40:13507)
2024-05-09 11:22:43     at async u (/app/.next/server/chunks/5566.js:40:13017) {
2024-05-09 11:22:43   cause: Error: unknown scheme
2024-05-09 11:22:43       at makeNetworkError (node:internal/deps/undici/undici:5840:35)
2024-05-09 11:22:43       at schemeFetch (node:internal/deps/undici/undici:10745:34)
2024-05-09 11:22:43       at node:internal/deps/undici/undici:10615:26
2024-05-09 11:22:43       at mainFetch (node:internal/deps/undici/undici:10634:11)
2024-05-09 11:22:43       at fetching (node:internal/deps/undici/undici:10582:7)
2024-05-09 11:22:43       at fetch (node:internal/deps/undici/undici:10446:20)
2024-05-09 11:22:43       at fetch (node:internal/deps/undici/undici:12617:10)
2024-05-09 11:22:43       at fetch (node:internal/bootstrap/web/exposed-window-or-worker:79:16)
2024-05-09 11:22:43       at i (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:177566)
2024-05-09 11:22:43       at F (/app/.next/server/chunks/1638.js:1:39684)
2024-05-09 11:22:43 }
2024-05-09 11:22:43 [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
2024-05-09 11:22:43   digest: '3395698411'
2024-05-09 11:22:43 }`

**Comment by JayGhiya** [comment]
I can check again then let's figure out if there is old data that is causing this in your K8s.

**Comment by acquia-ankith** [comment]
@JayGhiya Should we update this line in indexing-model-deployment.yaml 
`image: danswer/danswer-model-server:latest`
to use variable that can be updated with values.yaml ??

**Pull request merged**
