### PR TITLE
Making searching docs as a default option to reduce hallucinations

### PR DESCRIPTION
**Pull request by arslan70**
Fixes: https://github.com/danswer-ai/danswer/issues/881

### CODE REVIEW

**Comment by yuhongsun96** [comment]
Hello hello! Thanks so much for your contribution and thank you for your patience on the review. I like the idea and the fix. However since there are many different models people use, I think it may be best to provide this Llama2 prompt as an alternative rather than overwriting the base prompt that is tuned for GPT. We actually have a config for choosing prompts but currently there's only the "weak" model option. Perhaps you can extend it to support a version for Llama2 tuned prompts?

See here for reference: https://github.com/danswer-ai/danswer/blob/main/backend/danswer/one_shot_answer/factory.py#L39

Probably the simple prompt swap can be less involved than this but do make sure it works for both Chat and Search!

Let me know your thoughts?

**Comment by yuhongsun96** [comment]
Hi, not sure if @arslan70 will find the time to make the PR changes so that the prompts can be model specific. If he isn't able to do this, I will take it up sometime next week. In the meantime you can use his edits in the code directly and build from source. Would that work for you? @rohitrsh

**Comment by arslan70** [comment]
Hi @yuhongsun96 I spent some time trying to make a connection of the [factory](https://github.com/danswer-ai/danswer/blob/main/backend/danswer/one_shot_answer/factory.py#L39) with prompt overriding for llama2, but couldn't :(
Could you give me a little more details on how it would look like? 

My initial thought was to add an "if" [here](https://github.com/danswer-ai/danswer/blob/main/backend/danswer/secondary_llm_flows/choose_search.py#L61) but I think there is a more elegant solution with the factory.

**Comment by yuhongsun96** [comment]
Hey @arslan70, we've decided to make prompt sets for different models via yaml files for different LLMs. Do you want to just check in some good prompts you're using as just unused variables for now and in the next week or so we will add in the option to choose a prompt set and I'll include your version for Llama/Mixtral?

**Comment by yuhongsun96** [comment]
Hello, we haven't split out the prompts into per-model files but there is this environment variable to always trigger search. Most questions are answered well even if additional unnecessary context is provided so I definitely recommend turning it on!

DISABLE_LLM_CHOOSE_SEARCH=True

The container just needs to be aware of this. So if you're deploying with docker compose, it can be in the .env file.
More details here: https://docs.danswer.dev/configuration_guide

**Comment by rohitrsh** [comment]
Hey @yuhongsun96 ,

After enabling `DISABLE_LLM_CHOOSE_SEARCH=True`, this property in the config is working for me.

I will continue with my test from here.

Thank you for pointing me to the correct confirmation.

**Review by yuhongsun96 — APPROVED** [review]
Haven't gotten around to creating the templatized prompts for different LLMs. I'll just put it in the code for now as an alternative that people can easily switch to.

**Pull request merged**
