### PR TITLE
Minor/minimal UI

### PR DESCRIPTION
**Pull request by pablodanswer**
Modify the UI slightly.

Main changes / goals
- Reduce Clutter (attached doc toggle + dropdown for sources)
- Increase contrast (colored input + chat boxes)

Screenshot 2024-06-17 at 5 02 44 PM

### CODE REVIEW

**Comment by pablodanswer** [comment]
Small toggling animation
- Goes back to question: how dynamic should the UI be?

https://github.com/danswer-ai/danswer/assets/171597620/9e9dee4c-4944-4cd7-8edb-9061de3b166e

**Comment by foreveryh** [comment]
Good job!

**Comment by pablodanswer** [comment]
Quickly went ahead and aligned the headers to make the UI more cohesive. Before -> After

Screenshot 2024-06-18 at 12 56 47 PM

Screenshot 2024-06-18 at 12 57 51 PM

**Comment by pablodanswer** [comment]
Quick update to toggling!

https://github.com/danswer-ai/danswer/assets/171597620/23b956f0-ed04-49ff-838d-012169b59340

**Comment by foreveryh** [comment]
Thank you! Have you considered supporting mobile responsive design?

**Pull request closed without merging**
