### PR TITLE
feat: add Helm chart

### PR DESCRIPTION
**Pull request by arnaud-ritti**
Hi,

Has started on PR #1177 from @JayGhiya, i've also made a Helm Chart. May be we can merge our work to made a good chart for Danswer.

### CODE REVIEW

**Comment by JayGhiya** [comment]
@arnaud-ritti amazing lets talk today when you have time :) .

**Comment by arnaud-ritti** [comment]
Hi @JayGhiya, do you want to take a call ? You can book a slot here :) https://calendar.app.google/YpTwxoqwfWik23A77

**Comment by JayGhiya** [comment]
> Hi @JayGhiya, do you want to take a call ? You can book a slot here :) https://calendar.app.google/YpTwxoqwfWik23A77

Sure i will do that.

**Comment by JayGhiya** [comment]
Hey went through the files before our call scheduled today. also commented here - https://github.com/danswer-ai/danswer/pull/1177#issuecomment-1982676828 . So we will be going ahead with your pr as it meets more helm standards in terms of sub charts. So if you get time before out pr lets do couple of things:

- so it would be great if you could do helm dependency update inside your charts so that sub charts are also downloaded and part of same pr. 
- And from #1177 lets take openEbs for local deployment (otherwise charts will fail as two services - backend and api server use the same storage and it should be readWriteMany) i have added readme too for instructions. that also should be a subchart with enabled/disabled condition based on need.

**Comment by arnaud-ritti** [comment]
It's not recommended to commit chart dependencies, you should use `helm dependency build` instead. And for OpenEBS i agree it's a good option, but it can also be handled with Pods Affinity i think that it must be more stateless. For example you may want use Filestore if you are on GKE. A good documentation is better than add this constraint. Thats my opinion.

**Comment by JayGhiya** [comment]
> It's not recommended to commit chart dependencies, you should use `helm dependency build` instead. And for OpenEBS i agree it's a good option, but it can also be handled with Pods Affinity i think that it must be more stateless. For example you may want use Filestore if you are on GKE. A good documentation is better than add this constraint. Thats my opinion.

So overriding and config becomes way easier when subcharts are part of parent chart when they are packaged. Just an example of recent most used open source project that includes subcharts as part of package - https://github.com/SigNoz/charts. But will leave the final decision to you and maintainers of danswer. Yea we could document but from an end user experience in terms of immediately trying danswer it is v important to have some sort of local experience which is not possible without openebs. Without nfs helm charts won't work as api server and danswer backend use the same storage so i might not have understood the pod affinity relevance so if you could elaborate it could help.

**Comment by JayGhiya** [comment]
Current tasks:

- [ ] Create Hosted Vespa charts For Upstream so that could be used directly. 
- [ ] Add Vespa Hosted Charts as Dependency and override values as per danswer requirements in parent values.yaml
- [ ] Add Nginx as Dependency and override values as per danswer requirements in parent values.yaml
- [ ] Add OpenEbs as Depenency and override values as per danswer requirements in parent values.yaml
- [ ] Add Resource Requirments as per Danswer resource recommendations.
- [ ] Add Github CI/Cd for packaging and hosting danswer helm chart.
- [ ] Add Documentation for the same.

**Comment by JayGhiya** [comment]
will be working towards vespa charts for upstream today as vespa open source github repo still does not house helm charts.

**Comment by yuhongsun96** [comment]
Hey guys, thanks so much for the hard work on the Helm Charts! Sorry I haven't found time to review it, I promise I have not forgotten!

**Comment by JayGhiya** [comment]
no problem @yuhongsun96 :) intend to maintain the helm charts/cloud native things so that you guys can focus on business functions ! also hosted vespa charts are live. - https://github.com/unoplat/vespa-helm-charts . This also covers automatic changelog , git release and bump in chart yaml. the same process should help us in maintaining dasnwer helm charts. we will make our devSecOps awesome

**Comment by JayGhiya** [comment]
@arnaud-ritti could you grant me access to your repo so that I can continue making changes on the same repo so it becomes easy to collab

**Comment by JayGhiya** [comment]
thanks @arnaud-ritti got the access!

**Comment by JayGhiya** [comment]
Done with nginx changes!

**Comment by JayGhiya** [comment]
working on 1177 as it allows me to contribute faster otherwise here i have to create a branch as github does not allow to make changes to somebody else's pr and then do it.

**Comment by JayGhiya** [comment]
once 1177 is complete we can close this. have taken changes from here

**Comment by yuhongsun96** [comment]
Hey folks, in the latest version, we've removed the shared volume between the api server container and background container. It's all been moved to Postgres. Hopefully this simplifies things for the Helm deployment as well!

**Comment by yuhongsun96** [comment]
Finally got the chances to go through and review all this. Some things can be removed now but this is safe to put in as is and we can iterate on it in successive PRs so that this PR isn't too many versions out of date!

Thank you both so much @arnaud-ritti and @JayGhiya

**Comment by yuhongsun96** [comment]
@arnaud-ritti @JayGhiya, I've added a bit more context in https://github.com/danswer-ai/danswer/pull/1177

Thank you both for all the effort you've put into this and I'll be more active with you guys on this now that I have a bit more bandwidth

**Pull request merged**
