### PR TITLE
Refactor environment variable handling using ConfigMap for Kubernetes deployment

### PR DESCRIPTION
**Pull request by voarsh2**
Created to help this issue: https://github.com/danswer-ai/danswer/issues/514

It's a draft at the moment. Hoping to get some feedback. There are more env variables for docker-compose deployment that is not specified in the Kubernetes deployment .

- Refactored the code to use a ConfigMap for environment variables.
- Updated the `AUTH_TYPE` value in multiple deployment files to be fetched from the `env-configmap`.
- Updated the `DOMAIN` value in the nginx service deployment file to be fetched from the `env-configmap`.
- Updated the `INTERNAL_URL` value in the web server service deployment file to be fetched from the `env-configmap`.
- Added commented out variables for INTERNAL_MODEL_VERSION, QA_TIMEOUT, GEN_AI_MODEL_VERSION, and GEN_AI_API_KEY to the environment config map. These seem already hard-coded in the source code at the moment.
- Add necessary environment variables for Azure, OpenAI and set WEB_DOMAIN to http://localhost:3000.
- Removed hardcoded environment variable `VESPA_HOST` in deployment\kubernetes\api_server-service-deployment.yaml and use configmap
- Added new environment variables:
  - `INTERNAL_MODEL_VERSION` with value from config map
  - `GEN_AI_MODEL_VERSION` with value from config map
  - `GEN_AI_API_KEY` with value from config map
  - `GEN_AI_ENDPOINT` with value from config map
  - `GEN_AI_HOST_TYPE` with value from config map
  - `NUM_DOCUMENT_TOKENS_FED_TO_GENERATIVE_MODEL` with value from config map
  - `QA_TIMEOUT` with value from config map
  - `VALID_EMAIL_DOMAINS` with value from config map
  - `GOOGLE_OAUTH_CLIENT_ID` with value from secret key reference
  - `GOOGLE_OAUTH_CLIENT_SECRET` with value from secret key reference
  - `DISABLE_GENERATIVE_AI` with value from config map
  - `API_BASE_OPENAI`, `API_TYPE_OPENAI`, and `API_VERSION_OPENAI` are empty in the current commit, but they can be set later through the same mechanism.
- Updated values of existing environment variables:
  	- Set the value of INTERNAL_MODEL_VERSION to "openai-chat-completion"
  	- Set the QA_TIMEOUT to "60"
  	- Set the GEN_AI_MODEL_VERSION to "gpt-3.5-turbo"

### CODE REVIEW

**Comment by voarsh2** [comment]
I have now tested applying the YAML's locally, will test that they actually apply any custom config I set for the api-server deployment, etc as I expect

**Comment by yuhongsun96** [comment]
Hey, sorry for the slow response! We've been pretty swamped with requests recently.

I really like what you've done, I'll test it tomorrow and if there are no issues we can put it in.

> It's a draft at the moment. Hoping to get some feedback.

Regarding the above, what other things did you think of adding/fixing since you're saying this is a draft. And also what kind of feedback would be helpful? I mean I think this type of improved organization/separation/configurability is generally good.

**Comment by voarsh2** [comment]
> Hey, sorry for the slow response! We've been pretty swamped with requests recently.
> 
> I really like what you've done, I'll test it tomorrow and if there are no issues we can put it in.
> 
> > It's a draft at the moment. Hoping to get some feedback.
> 
> Regarding the above, what other things did you think of adding/fixing since you're saying this is a draft. And also what kind of feedback would be helpful? I mean I think this type of improved organization/separation/configurability is generally good.

Thanks for your reply.
I suppose regarding feedback, your comment about liking it is probably enough (what I wanted).
I don't know the codebase enough to know if there is anything else missing for configmap, or if you'd like anything different.

Let me know how the testing goes

**Comment by yuhongsun96** [comment]
Let me know if this is ready, I'll be happy to test it and put it in

**Comment by voarsh2** [comment]
I haven't had time to go over adding more variables to the config map.
I tried a recent commit (merging recent changes... e.g confluence on prem) and the WB_DOMAIN variable was giving me issues with the Google sign-on, I was being redirected to [domain]:3000, not the standard 80/443 port. This behaviour is unexpected, and I can't workout what change in master is causing this just yet. Any ideas?

**Comment by yuhongsun96** [comment]
Hi, any luck getting around the port issue? Nothing really changed around that recently, do let us know if you find the root cause. If you need help, let me know!

**Comment by voarsh2** [comment]
It might be something to do with the nginx config - I am piggy backing off of the service which is at port :3000 so the google login is redirecting back to that port... Will play around with that when I have some more time.

I also notice that the docker-compose.prod.yml references "model" server - but no new service has been made for Kubernetes. Haven't looked around to see what it's doing and if it's needed for Kubernetes deployment?

**Comment by yuhongsun96** [comment]
The model server is a container that serves up the NLP models that are used by Danswer. There's now an option to use that rather than running the NLP models locally in memory. This allows having a dedicated GPU instance for all things model related.

Up to you if you want to include the option in the kubernetes deployment. Either way is fine.

For docker compose it's under a profile, you'd use run it with --profile model-server

**Comment by voarsh2** [comment]
> The model server is a container that serves up the NLP models that are used by Danswer. There's now an option to use that rather than running the NLP models locally in memory. This allows having a dedicated GPU instance for all things model related.
> 
> Up to you if you want to include the option in the kubernetes deployment. Either way is fine.
> 
> For docker compose it's under a profile, you'd use run it with --profile model-server

Might save that for another PR.

I think it's ready for you to test. I'm sure the :3000 redirecting issue is because of the ClusterIP port and nginx.
Can you give this PR a test soon? Would be nice to know if you have the :3000 issue upon logging in via Google

**Comment by szymon-planeta** [comment]
Hi @voarsh2 , I was looking at k8s deployment and also encountered :3000 google oauth redirect issue. It seems like `WEB_DOMAIN` env is missing from `deployment/kubernetes/web_server-service-deployment.yaml` but is referenced in `web/src/lib/redirectSS.ts`. After setting `WEB_DOMAIN` for web server my google oauth flow is working fine (for nginx + CluterIP)

**Review by yuhongsun96 — APPROVED** [review]
Thanks a bunch for your contribution! Super important change for our K8s users.

I rebased and updated some of the values for you. Thanks again! :D

**Pull request merged**
