### PR TITLE
Tremor -> Shadcn

### PR DESCRIPTION
**Pull request by pablodanswer**
## Description
[Provide a brief description of the changes in this PR]

## How Has This Been Tested?
[Describe the tests you ran to verify your changes]

## Accepted Risk (provide if relevant)
N/A

## Related Issue(s) (provide if relevant)
N/A

## Mental Checklist:
- All of the automated tests pass
- All PR comments are addressed and marked resolved
- If there are migrations, they have been rebased to latest main
- If there are new dependencies, they are added to the requirements
- If there are new environment variables, they are added to all of the deployment methods
- If there are new APIs that don't require auth, they are added to PUBLIC_ENDPOINT_SPECS
- Docker images build and basic functionalities work
- Author has done a final read through of the PR right before merge

## Backporting (check the box to trigger backport action)
Note: You have to check that the action passes, otherwise resolve the conflicts manually and tag the patches.
- [ ] This PR should be backported (make sure to check that the backport attempt succeeds)

### CODE REVIEW

**Comment by Weves** [comment]
A few items I noticed:

Button should probably be blue like before:
Screenshot 2024-10-31 at 7 13 38 PM

Table has a judder after a re-order:
https://github.com/user-attachments/assets/cd4f010e-c940-40bf-9a32-7efe47b2573f

Connector table missing sides:
Screenshot 2024-10-31 at 7 15 12 PM

Color for "Paused" should stay consistent (prefer keeping it as yellow for now, to limit changes):
Screenshot 2024-10-31 at 7 17 35 PM
Screenshot 2024-10-31 at 7 17 40 PM

Too many horizontal lines in a row (maybe can add a title to the table similar to the API Keys page):
Screenshot 2024-10-31 at 7 18 46 PM


Screenshot 2024-10-31 at 7 21 09 PM

**Comment by yuhongsun96** [comment]
image
Let's keep these green, green for GO!

**Comment by yuhongsun96** [comment]
image
This one also for now. Though in the future I think we'll use our "pop" color probably

**Comment by yuhongsun96** [comment]
image
public was green previously

**Comment by yuhongsun96** [comment]
image
same as what Chris pointed out but on a different page, the second line after the Search connectors bar should be gone

**Comment by yuhongsun96** [comment]
Also on the connector table, if you collapse or expand it, it shifts a little bit left and right.

This is a bug on the existing but should be an easy fix: toggling a single row will make the "collapse all" or "expand all" swap back and forth. It should show expand all unless all are expanded I think.

**Comment by yuhongsun96** [comment]
image
Just in general, a lot of colors should be green to be consistent with what there is today

**Comment by yuhongsun96** [comment]
image

Only fix if it's fast (this is the same as the existing anyhow). I think it's a bit too narrow or something? Feels kind of off

**Comment by yuhongsun96** [comment]
image
Set Retention Limit was green and right now Retain All is too light colored. It was blue formerly, probably ok to just keep it blue

**Comment by yuhongsun96** [comment]
image
image

Color and spacing are different, I think also there is a new line at the bottom

**Comment by yuhongsun96** [comment]
image
Green here too I guess

**Review by trial-danswer — APPROVED** [review]

**Pull request merged**
