### PR TITLE
Merged background and api-server images

### PR DESCRIPTION
**Pull request by ssddanbrown**
This PR merges two of the docker images, background and api-server, into a single api-server image.
These two images are very large due to their dependency lists, requiring a ~3.5GB download for each image. For the same reasons, these images can each take a large amount of time to build.
This could act as a bit of a barrier for use and development.

When looking at the `Dockerfile` used by the two images, I noticed they were very similar.
This PR merges the Dockerfiles, so a single image can be built to be shared across the two services.
The background service will now use "updated/merged" api-server image, but specify a different command via the docker-compose setup so it can run it's separate operation.

I have tested this locally and everything seems to work as expected.

I have not updated the `docker-compose.prod.yml`, since I wasn't sure how this is actually used, but this may also need an update. It's possible I've missed other files that may be related to the images.

Lastly, I'm aware I did not discuss this prior via an issue/discord/slack, so if this is not a direction you'd want to go I'd fully understand, I simply worked on this out of my own curiosity after thinking about it while waiting for the two images to download earlier today.

### CODE REVIEW

**Comment by yuhongsun96** [comment]
Hey, this looks like a great improvement to me! Can go ahead and make the change to the prod file as well.

What's the thinking behind having a default command in the Dockerfile which is for the API server rather than having both be specified via docker compose? (not that this is wrong, just want to hear your thoughts)

Also please make this work for the kubernetes deployment as well, the containers will also need to be passed the right command to run.

@Weves, any additional thoughts?

**Comment by ssddanbrown** [comment]
Thanks for the feedback @yuhongsun96.

> What's the thinking behind having a default command in the Dockerfile which is for the API server rather than having both be specified via docker compose? 

No major reason for this, I was just aiming to change things up as little as possible. Thought I might as well leave a command for one of those services in there as a default, and just specify for the other.

> Can go ahead and make the change to the prod file as well.

Sure, I'll make this change.

> Also please make this work for the kubernetes deployment as well

Ah, okay. I've never used K8s before but I'll give it a go.

**Comment by yuhongsun96** [comment]
Sounds good! let me know if you have any trouble with K8s, happy to help out

**Comment by ssddanbrown** [comment]
Alright, I've now updated the prod compose file, and the k8s config.
I ran a test of the k8s config against my local dev image build, using minikube and all seemed to work as expected.

**Review by yuhongsun96 — APPROVED** [review]
Looks great! Thank you for the good work!

**Pull request merged**
