### PR TITLE
Support for compressed sitemap, sitemap index, and robots.txt

### PR DESCRIPTION
**Pull request by zotya**
Upgraded the sitemap variant of the web connector to use [ultimate_sitemap_parser](https://pypi.org/project/ultimate-sitemap-parser/)
Benefits:
- we don't have to specify the sitemap, ultimate_sitemap_parser will automatically try to search for it
- compressed sitemap.xml is supported
- sitemap index is supported

Also, we take in account the robots.txt, using [urllib.robotparser](https://docs.python.org/3/library/urllib.robotparser.html)

If you prefer, you can still specify the exact location of the sitemap, and the connector will use that sitemap.

### CODE REVIEW

**Review by yuhongsun96 — APPROVED** [review]
Looks good!

**Review by yuhongsun96 — APPROVED** [review]
Ah, could you rebase the changes please, ty!

**Comment by zotya** [comment]
> Ah, could you rebase the changes please, ty!

Sorry for the delay, I did the rebase now.

**Comment by yuhongsun96** [comment]
Awesome thanks!

**Pull request merged**
